//程序配置文件
export default{
    Dock:{
      element:require("../components/Dock/Dock"),
      noPushDock:true,//不把程序加入Dock
    },
    Clock:{
      element:require("../components/Clock/Clock"),
      noPushDock:true,//不把程序加入Dock
    },
    Search:{
      element:require("../components/Search/Search"),
      noPushDock:true,//不把程序加入Dock
      data:{
        test:'test'
      },//自定义数据
    },
    ImgBrowser:{
      name:'图片',
      procedureName:'ImgBrowser',
      icon:require('./img/photo.svg'),
      element:require("../components/ImgBrowser/ImgBrowser"),
      width:600,//程序的宽
      height:500,//程序的高
    },
    Set:{
      name:'设置',
      procedureName:'set',
      icon:require('./img/set.svg'),
      element:require("../components/Set/Set"),
      width:400,//程序的宽
      height:500,//程序的高
    },
    BgSet:{
      name:'壁纸',
      procedureName:'bgP',
      icon:require('./img/pic.svg'),
      element:require("../components/BgSet/BgSet"),
    },
    HistoryList:{
      name:'标签',
      procedureName:'HistoryList',
      icon:require('./img/tag.svg'),
      element:require("../components/HistoryList/HistoryList"),
    },
    Weather:{
      name:'天气',
      procedureName:'Weather',
      noPushDock:true,//不把程序加入Dock
      element:require("../components/Weather/Weather"),
    },
    SystemPanel:{
      name:'系统监控面板',
      procedureName:'SystemPanel',
      noPushDock:true,//不把程序加入Dock
      element:require("../components/SystemPanel/SystemPanel"),
    }
}